version: '3'

# https://github.com/SeleniumHQ/docker-selenium/wiki/Getting-Started-with-Docker-Compose
services:

  puppeteer:
    image: zenato/puppeteer-renderer
    volumes:
      - "${PROJECT_ROOT}:/app/adapter" # this is carefully placed into the puppeteer /app from the image
    working_dir: '/app/adapter'
    environment:
      - DEBUG=${DEBUG}
      - ENTRY=${ENTRY}
      - PROJECT_ROOT=${PROJECT_ROOT}
      - RELATIVE_CONFIG_FILE=${RELATIVE_CONFIG_FILE}
      - RELATIVE_RESULTS_DIR=${RELATIVE_RESULTS_DIR}
      - RELATIVE_SNAPS_RUN_DIR=${RELATIVE_SNAPS_RUN_DIR}
      - STATIC=${STATIC}
    command: ['node', "${ENTRY}"]

  static:
    image: node:alpine
    volumes:
      - "${PROJECT_ROOT}:/adapter"
      - "${STATIC}:/static"
    expose:
      - 3333
    command: ["node", "/adapter/node_modules/.bin/httpster", "-d", "/static"]
